### ISSUE TITLE
Cannot create new notebook inside Drive tab

### ISSUE THREAD

**Issue by mirestrepo** [jupyterlab/jupyterlab-google-drive#138] opened 2018-08-21 04:00 UTC
I am running this extension within JupyterHub (a typical setup of k8+docker-stacks). I can create new directories and text files within the drive with no problem. However when I select to add a new notebook, instead of adding the file to my drive, it adds it to my /home/joyvan folder within the hub (I can see it in the files tab, but not in my drive tab). Is there some further configuration that I need to do? I'm running JupyterLab 0.33. If I already have a notebook in the drive, it renders and runs correctly

Thanks

**Comment by ian-r-rose** [comment] 2018-08-21 12:26
Thanks for the report @mirestrepo! This is a pretty major regression, and definitely not intended. I've just opened jupyterlab/jupyterlab#5175 with a fix for this.

**Closed** 2018-08-21 19:31 UTC
Labels: type:Bug

**Comment by ian-r-rose** [comment] 2018-08-21 20:13
Hi @mirestrepo, we have just published JupyterLab v0.34.1, which contains a fix for this. Can you update your install?

**Comment by mirestrepo** [comment] 2018-08-30 14:08
@ian-r-rose Sorry for the delay - In order to test JupyterLab v0.34.1, I needed to update the Hub (which had other implications) but on update, it worked as expectedly! Thanks for the prompt fix!
