### ISSUE TITLE
Does not yet support the current version 

### ISSUE THREAD

**Issue by vikjin** [jupyterlab/jupyterlab-google-drive#208] opened 2022-04-06 21:54 UTC
## Description
<img width="804" alt="Screen Shot 2022-04-06 at 2 53 10 PM" src="https://user-images.githubusercontent.com/101016665/162078194-11a67e15-82f2-4642-a0a1-60b8fad7f26b.png">

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by andydoc** [comment] 2022-09-18 08:43
This is a duplicate of a previous issue. Please close and merge

**Closed** 2023-08-03 16:55 UTC
