### ISSUE TITLE
File changed dialog shows while any change made

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#14] opened 2017-06-08 16:56 UTC
After running cell of notebook in Google drive, the file changed dialog shows. 

<img width="508" alt="screen shot 2017-06-07 at 3 35 29 pm" src="https://user-images.githubusercontent.com/4332577/26940653-57a04eb8-4c30-11e7-9d46-be538bc59db1.png">

It probably causes autosave does not sync up with real time api. Is there any way to disable autosave?

thanks

**Comment by ian-r-rose** [comment] 2017-06-08 16:59
Yep, the issue is that the autosaver checks the timestamp of the file before saving, and throws up a warning if it has changed more recently than it expected. If two users are editing the same file, this causes an unwanted conflict.

This has been addressed in jupyterlab/jupyterlab#2387 (which disables the warning dialog), and will be available in the next release.

**Comment by ktong** [comment] 2017-06-08 17:55
thanks. Hope it's fixed in next release. You mentioned that it's happened when two users are editing same file. But even only me editing the file, the dialog still shows.

**Comment by ian-r-rose** [comment] 2017-06-16 15:00
Hi @ktong, we've just released JupyterLab v0.24.0 and JupyterLab Google Drive v0.2.0, which include the fix for this problem. Might you check to see if it does the trick for you?

**Comment by ktong** [comment] 2017-06-16 18:33
Thanks, will check it after vacation

**Comment by ktong** [comment] 2017-06-20 17:31
It seems good after upgrade lab to 0.24.*

**Closed** 2017-06-20 17:31 UTC
Labels: status:Needs User Testing, tag:Real Time Collaboration, type:Bug
