### ISSUE TITLE
Decreased performance/reliability with JL 0.30 and JGD 0.9

### ISSUE THREAD

**Issue by jochym** [jupyterlab/jupyterlab-google-drive#113] opened 2017-12-11 15:48 UTC
The extension was working very nicely and reliably with earlier versions of JL (0.27-0.28 if I remember correctly). After upgrade to 0.30 the GD-integration slowed down and became unreliable. Essentially any notebook above 300-400kb in size stopped loading (they still works fine from the remote notebook server).
It is a real pity - since gd-based notebooks were simply great for collaboration.

To introduce the move premiere theme:
Help us @ian-r-rose, you are our only hope ;)

**Comment by blink1073** [comment] 2017-12-11 16:00
Hi @jochym, this could be a rate throttling on the part of Google given their deprecation of the real time API (cf #108).

**Comment by jochym** [comment] 2017-12-11 16:18
If it would help I can make a test local  install of previous version (using the same api key) and check if this is indeed regression or rate throttling. How to install particular version of the lab/gd-extension?

**Comment by ian-r-rose** [comment] 2017-12-11 16:22
That would be useful. There have been few changes in this extension that I think would cause changes in performance.
You can install a specific version of Lab/GDrive using
```bash
pip install jupyterlab==0.28
jupyter labextension install @jupyterlab/google-drive@0.7.0
```
(substitute versions as necessary).

**Comment by jochym** [comment] 2017-12-11 16:23
Thanks. I'll report if I have any new data.

**Comment by ian-r-rose** [comment] 2017-12-11 16:25
Thanks, @jochym!

**Comment by jochym** [comment] 2017-12-11 20:17
Ok. I was able to easily reproduce the issue on the clean install (using the same gdrive account). 
- On JL 0.29.2 + JLGD 0.8.0 everything works reasonably well (I am on residential internet at the moment)
- On JL 0.30.6 + JLGD 0.9.0 notebook loading is much slower and some cannot be opened at all (eternal spinner). Generally it depends on the size of the notebook but sometimes even small ones do not open.

I'm getting back to 0.29.2/0.8.0 for "production" but I have test install I can test on. Let me know if I can help in any way.

**Comment by ian-r-rose** [comment] 2017-12-29 20:19
Hi @jochym, I have been experimenting with comparisons between `v0.29.2`/`v0.8.0` and `v0.31`/`v0.10.0`, and I have not been able to reproduce any significant or consistent performance differences between them. The notebooks I have been trying have ranged from very small to ~1Mb. Are there any updates on your end regarding the performance?

**Comment by jochym** [comment] 2018-01-12 11:36
Just installed v0.31/v0.10.0 and the problems continue. I routinely use 0.29 for day-to-day work so I have real world comparison. The setup involves remoto operation (server in the institute) and local and remote network operation. I need to run on my own clientid setup (kernels running on the server and communication to public server address over https and non-standard port. 
The problems are two/three-fold:
- The performance is bad in comparison with 0.29
- Even worse on firefox
- Real time collaboration stopped working

Can I try anything to help improving this? The lab with real time collaboration is so useful for team work that I can hardly think of going back to the old ways of doing things. It may be my setup at fault, it is not quite simple - but it works fine on 0.29!

**Comment by jochym** [comment] 2018-01-12 11:43
I found the problem with RTC at least - It does not work across versions!
If I try two browsers with the same version installed the RTC works - so you can scratch the last point above. __Please add a big fat warning about not crossing the versions!__ There is a substantial possibility of data loss - better warn the users!
The performance is still down, particularly on firefox. I'll keep you posted.

**Comment by ian-r-rose** [comment] 2018-01-12 16:01
Thanks for the update @jochym, sorry to hear about that (though note that as of yesterday, the current version is 0.11.0). Is it correct to say that you are finding the decreased performance here to be *in addition* to the problems you describe in jupyterlab/jupyterlab#1639? That is to say, you think they are separate and compounding issues?

Two browsers with different versions *should* still work if the underlying data model has not changed (which it has not, for ~6 months). However, they *will not* work if the client ID is different (with a possibility for data loss! See the note [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/troubleshooting.md#i-have-shared-a-document-with-another-person-but-they-dont-seem-to-by-synchronizing)). Is it possible that you inadvertently had different client ids in the two different browser versions?

**Comment by lstillwe** [comment] 2018-01-13 15:34
I am having a similar issue where I can log into, and see files listed on my Google Drive. However, when I try to create new, or open existing notebooks there, a new tab opens in JupyterLab but hangs (spinning ball) forever with no content loaded.

My environment:

I have JupyterLab with the google-drive extension, installed in JupyterHub

Here are the versions:
# pip freeze | grep jupyter
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
jupyterhub==0.7.2
jupyterlab==0.30.6
jupyterlab-launcher==0.6.0

# jupyter labextension list
JupyterLab v0.30.6
Known labextensions:
   app dir: /opt/anaconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.31.3  enabled  OK
@jupyterlab/google-drive
        @jupyterlab/google-drive v0.9.0  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.7.0  enabled  OK

Also, I did all the steps listed [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md#Realtime-API) to set up Google APIs, and set the clientId with my credentials key in the Google Drive settings.

Does anyone else have this issue? Is there anything I am missing, or is not configured correctly?
Please let me know if you need more info, or how to turn on additional logging to get more clues.

**Comment by ian-r-rose** [comment] 2018-01-13 17:06
@lstillwe Can you check if there are any errors being output to the Javascript console in your browser?

Also, is this a new set of credentials you have set up with the Google APIs? As discussed in #108, we have recently had to change the setup the web app to handle the case with no realtime API. Can you verify that you have set the `realtime: false` setting, as described [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md#realtime-api)?

We are still responding to the deprecation, and it is possible that we need to tweak our instructions/setup further.

**Comment by lstillwe** [comment] 2018-01-13 18:26
Thanks @ian-r-rose. The javascript console seems to show that it is a problem associated with  the realtime api: "Drive Realtime API Error: forbidden: Access denied to file."

I tried to set the "realtime" setting to false in the settings for GoogleDrive but the interface said I had a syntax error and would not let me save the setting:

<img width="315" alt="jhub_pic" src="https://user-images.githubusercontent.com/1794116/34908859-042cddb4-f865-11e7-9880-cbdbcdadd1e0.png">

What should the syntax be for this? Thanks again!

**Comment by ian-r-rose** [comment] 2018-01-13 20:43
It looks like you are missing a comma at the end of the clientId field.

**Comment by lstillwe** [comment] 2018-01-13 21:59
Doh! I guess I just copied the system defaults over and didn't notice that was missing.
Thanks you for all your help - it is working now - sans realtime as expected.

**Comment by jochym** [comment] 2018-02-03 22:42
Sorry @ian-r-rose - your question slipped my attention. Yes this issue is an additional problem to the one reported in https://github.com/jupyterlab/jupyterlab/issues/1639. This makes JL with GD really frustrating. If the notebook loads it works fine or at least acceptable. But it is really hard to load it - sometimes you need to try 10-20 times before it loads. And it is worse when tested on remote server (remote jupyterhub install on our cluster) comparing to local JL session accessing the same GD hosted notebooks. Locally it is slightly better but the problem still exists.

**Comment by ian-r-rose** [comment] 2018-02-03 23:16
Unfortunately, I am still unable to reproduce this issue (though we are working through some performance fixes in core JupyterLab which will hopefully help somewhat). I just tried a remote JupyterHub deployment and used GD to open a ~6Mb notebook as well as one with ~100 cells. Both worked (with the caveats of the performance issues in JLab).

For the times when the load fails, have you seen any errors on the Javascript console?

**Comment by jochym** [comment] 2018-02-03 23:32
Maybe this is just my particular deployment which is at fault? 
There is a bunch of:
`Failed to load resource: the server responded with a status of 400 ()` from drive.google.com
and 
`Drive Realtime API Error: server_error: Server returned unexpected HTTP status: 500` and 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://wolf.ifj.edu.pl:8443' is therefore not allowed access. The response had HTTP status code 409.
Naturally a bunch of other JS errors follow. I can make a more isolated session to test this further. Will this help?
This is not particularly slow connection (50/5 mbit/s residential network), and we have the same behavior on the lan connected to multi Gbit national research network.

**Comment by ian-r-rose** [comment] 2018-02-04 00:02
Yes, I think an isolated case would help, especially if you see a difference in any messages between the times when it succeeds and the times when it fails. Sometimes the realtime API can throw a 500 error and be able to recover, and sometimes it cannot.

Thanks for cranking through this @jochym, I know this has been a frustrating issue.

**Comment by ian-r-rose** [comment] 2018-02-04 18:21
Oh, interesting! That code path is indeed new as of `0.30`, and involves `stderr` and `stdout`. Can you check if the notebooks that fail to load have `stdout` or `stderr` outputs? Or if the ones that succeed don't have any of those?

**Comment by jochym** [comment] 2018-02-04 18:33
There is no pattern in notebooks which fail. The same one can load fine once and next time it will fail without any changes to the contents.

**Comment by blink1073** [comment] 2018-02-04 20:23
This seems like another reason to investigate using `xterm.js` 3.0 for rendering `stderr` and `stdout`, rather than trying to do it ourselves.  cf https://github.com/jupyterlab/jupyterlab/issues/3773#issuecomment-362859209

**Comment by ian-r-rose** [comment] 2018-02-04 20:34
@blink1073 that is probably more reliable.

For this specific problem, it is looking like the JSON values that are retrieved from the realtime model are sometimes (but not always) immutable. I can't really see a pattern as to when this happens. The `_removeOverwrittenCharacters` mutates the JSON object text field, which is causing the error. We can make a deep copy of the relevant object before handing it out to see if that fixes the problem.

@jochym, I have pushed a branch that has this change. Would you be able to check if it improves the situation?
https://github.com/jupyterlab/jupyterlab-google-drive/tree/mutable_objects

**Comment by jochym** [comment] 2018-02-04 21:51
Sure if you tell me how to install this branch. The test system is fully independent from my production setup so it can experiment freely.

**Comment by ian-r-rose** [comment] 2018-02-04 22:39
You can install the branch by:
1. Cloning the repository and entering its directory.
2. Checking out the `mutable_objects` branch.
3. Build the extension by running `jlpm install && jlpm run build`
4. Install the local extension by running `jupyter labextension install .`

**Comment by jochym** [comment] 2018-02-04 22:46
Just applying https://github.com/jupyterlab/jupyterlab/pull/3805 seemed to improve situation a bit (definitely firefox *and* chrome load faster).
I'll install the branch and report.

**Comment by jochym** [comment] 2018-02-04 23:27
It seems it helped. The errors are gone and I was able to load a 20 notebook session flawlessly (albait slowly). Thanks. When we can expect inclusion of this change in the package?

**Comment by jochym** [comment] 2018-02-04 23:49
One more thing. How to permanently change the notebook css? The changes applied in `share/jupyter/lab/staging/node_modules/@jupyterlab/notebook/style` seem to not stick after build.

**Comment by jochym** [comment] 2018-02-05 00:28
I have moved the fix to the production env and it also works fine. Please release it soon.

**Comment by ian-r-rose** [comment] 2018-02-05 01:02
Hi @jochym, we plan to make releases of this (as well as the core JupyterLab with some of the performance improvements) on Monday or Tuesday.

The `403` errors are indeed due to rate-limiting, and there is not too much to be done about those, unfortunately.

**Comment by ian-r-rose** [comment] 2018-02-05 20:47
Hi @jochym, JupyterLab v0.31.3 and `@jupyterlab/google-drive` v0.11.1 have been released, which includes the fix for this, as well as some performance enhancements. Let me know if this improves things for your setup.

**Comment by jochym** [comment] 2018-02-05 21:21
Yep! The problem is solved. And the performance under firefox is _much_ better.
THANKS!

**Comment by blink1073** [comment] 2018-02-05 21:24
Awesome sauce, thanks to @ian-r-rose for the keen eye in fixing these bugs and @jochym for the follow up!

**Comment by ian-r-rose** [comment] 2018-02-05 21:27
Glad to hear it! Closing this turbulent issue.

**Closed by ian-r-rose** 2018-02-05 21:27 UTC
