### ISSUE TITLE
noSessionBound error when serving on port 80

### ISSUE THREAD

**Issue by cforelle** [jupyterlab/jupyterlab-google-drive#94] opened 2017-10-13 09:06 UTC
**See comment below--this actually seems to have to do with port 80**

Hello,

I am running into errors--I presume with authentication--on JupyterHub. Here is my setup:

*JupyterHub running in a Docker container on localhost, serving on port 80.
*Google OAuth used to authenticate to JupyterHub
*Installed @jupyterlab/plotly-extension, @jupyterlab/google-drive and @jupyterlab/hub-extension
*Manually overriding `clientId` in the Settings page of the extension.
*In Google Developers Console, localhost and localhost:80 are both allowed as origins.

The extension appears to load (I see it in the left-hand rail on JupyterLab), but I cannot log in to my Drive account. The behavior is slightly different on Chrome and Safari:

**Chrome**
No "Sign In" button appears below the big Google Drive icon. There is a `noSessionBound` error in the console on page load. 
![screen shot 2017-10-13 at 9 57 14 am](https://user-images.githubusercontent.com/10046979/31538308-0de22842-affd-11e7-9db6-f58389439ffc.png)

**Safari**
The "Sign In" button does appear below the big Google Drive icon. Clicking it pops up the usual Google authentication window, and the name of the application displayed corresponds to the name I gave my application in the Google Developers Console, so the `clientId` is getting properly overridden. But then nothing happens--the extension still shows the "Sign In" button, and I am no signed in. 
There is a similar error in the console (fyi, the line number corresponds to the same spot in the gap code as the Chrome error--just Chrome has prettified the code so line numbers are different):
![screen shot 2017-10-13 at 10 02 43 am](https://user-images.githubusercontent.com/10046979/31538514-bb3dc730-affd-11e7-8bc8-f80c9b3dbae8.png)

I suspect this has something to do with the authorized origin not being correct, but I am stumped. To try to rule out any kind of conflict between Google sessions, I created a new set of credentials as well, separate from the ones used for the JupyterHub OAuth, but that didn't help.

**Comment by cforelle** [comment] 2017-10-13 10:35
I tried mimicking my setup without JupyterHub (i.e., JupyterLab running on port 80 `sudo jupyter lab --port=80 --allow-root`) and I got the same errors. So my assumption is this has to do with the port. Not sure how to resolve, though.

**Comment by ian-r-rose** [comment] 2017-10-13 15:34
I am not sure what the problem is at the moment, but there are a couple of things we can try:
1. Have you tried to run the same thing on a port with fewer security restrictions (such as 8xxx)? This would let us know if the rest of your app is configured correctly in the Google Developer console.
2. Sometimes browser privacy controls can block the functioning of the plugin. If you have any of these enabled (third party cookie blocking, plugins, etc), try disabling them to see if that helps. Although the fact that you run into problems with both Chrome and Safari seems to make this less likely.

**Comment by cforelle** [comment] 2017-10-13 20:20
-Yes, it's working as expected with port 8888. (Just `jupyter lab`.) But port 80 (`sudo jupyter lab --port=80 --allow-root`) results in the error. I'm running a JupyterLab session here, not my JupyterHub setup.
-No browser privacy controls.

I'm befuddled!

**Comment by ian-r-rose** [comment] 2017-10-13 20:21
I am as well! I have just successfully reproduced the issue though, so there is at least that.

**Comment by jochym** [comment] 2017-10-20 19:36
It turns out the problem in https://github.com/jupyterlab/jupyterlab-google-drive/issues/93 is at least connected with this one, if not the same...

**Comment by ian-r-rose** [comment] 2017-11-12 02:29
Hi @cforelle , it took a bit longer than I anticipated to figure out a workaround for this, but I have just published `v0.8.0`, which includes a fix for this. Let me know if that works for your use case.

**Comment by cforelle** [comment] 2017-11-13 11:15
Yes! This is great. Thanks!

**Comment by ian-r-rose** [comment] 2017-11-13 14:50
Closed by #97

**Closed by ian-r-rose** 2017-11-13 14:50 UTC
Labels: tag:Login/Authentication, type:Question

**Comment by jochym** [comment] 2017-11-13 16:08
Great, thanks!
